python source/basegnn.py --dataset Mutagenicity --gnn_type gcn --runs 1
python source/basegnn.py --dataset Mutagenicity --gnn_type gcn --runs 2
python source/basegnn.py --dataset Mutagenicity --gnn_type gcn --runs 3
python source/basegnn.py --dataset Mutagenicity --gnn_type gat --runs 1
python source/basegnn.py --dataset Mutagenicity --gnn_type gat --runs 2
python source/basegnn.py --dataset Mutagenicity --gnn_type gat --runs 3
python source/basegnn.py --dataset Mutagenicity --gnn_type gin --runs 1
python source/basegnn.py --dataset Mutagenicity --gnn_type gin --runs 2
python source/basegnn.py --dataset Mutagenicity --gnn_type gin --runs 3
python source/basegnn.py --dataset Mutagenicity --gnn_type sage --runs 1
python source/basegnn.py --dataset Mutagenicity --gnn_type sage --runs 2
python source/basegnn.py --dataset Mutagenicity --gnn_type sage --runs 3
python source/basegnn.py --dataset Proteins --gnn_type gcn --runs 1
python source/basegnn.py --dataset Proteins --gnn_type gcn --runs 2
python source/basegnn.py --dataset Proteins --gnn_type gcn --runs 3
python source/basegnn.py --dataset Proteins --gnn_type gat --runs 1
python source/basegnn.py --dataset Proteins --gnn_type gat --runs 2
python source/basegnn.py --dataset Proteins --gnn_type gat --runs 3
python source/basegnn.py --dataset Proteins --gnn_type gin --runs 1
python source/basegnn.py --dataset Proteins --gnn_type gin --runs 2
python source/basegnn.py --dataset Proteins --gnn_type gin --runs 3
python source/basegnn.py --dataset Proteins --gnn_type sage --runs 1
python source/basegnn.py --dataset Proteins --gnn_type sage --runs 2
python source/basegnn.py --dataset Proteins --gnn_type sage --runs 3
python source/basegnn.py --dataset Mutag --gnn_type gcn --runs 1
python source/basegnn.py --dataset Mutag --gnn_type gcn --runs 2
python source/basegnn.py --dataset Mutag --gnn_type gcn --runs 3
python source/basegnn.py --dataset Mutag --gnn_type gat --runs 1
python source/basegnn.py --dataset Mutag --gnn_type gat --runs 2
python source/basegnn.py --dataset Mutag --gnn_type gat --runs 3
python source/basegnn.py --dataset Mutag --gnn_type gin --runs 1
python source/basegnn.py --dataset Mutag --gnn_type gin --runs 2
python source/basegnn.py --dataset Mutag --gnn_type gin --runs 3
python source/basegnn.py --dataset Mutag --gnn_type sage --runs 1
python source/basegnn.py --dataset Mutag --gnn_type sage --runs 2
python source/basegnn.py --dataset Mutag --gnn_type sage --runs 3
python source/basegnn.py --dataset AIDS --gnn_type gcn --runs 1
python source/basegnn.py --dataset AIDS --gnn_type gcn --runs 2
python source/basegnn.py --dataset AIDS --gnn_type gcn --runs 3
python source/basegnn.py --dataset AIDS --gnn_type gat --runs 1
python source/basegnn.py --dataset AIDS --gnn_type gat --runs 2
python source/basegnn.py --dataset AIDS --gnn_type gat --runs 3
python source/basegnn.py --dataset AIDS --gnn_type gin --runs 1
python source/basegnn.py --dataset AIDS --gnn_type gin --runs 2
python source/basegnn.py --dataset AIDS --gnn_type gin --runs 3
python source/basegnn.py --dataset AIDS --gnn_type sage --runs 1
python source/basegnn.py --dataset AIDS --gnn_type sage --runs 2
python source/basegnn.py --dataset AIDS --gnn_type sage --runs 3
python source/basegnn.py --dataset NCI1 --gnn_type gcn --runs 1
python source/basegnn.py --dataset NCI1 --gnn_type gcn --runs 2
python source/basegnn.py --dataset NCI1 --gnn_type gcn --runs 3
python source/basegnn.py --dataset NCI1 --gnn_type gat --runs 1
python source/basegnn.py --dataset NCI1 --gnn_type gat --runs 2
python source/basegnn.py --dataset NCI1 --gnn_type gat --runs 3
python source/basegnn.py --dataset NCI1 --gnn_type gin --runs 1
python source/basegnn.py --dataset NCI1 --gnn_type gin --runs 2
python source/basegnn.py --dataset NCI1 --gnn_type gin --runs 3
python source/basegnn.py --dataset NCI1 --gnn_type sage --runs 1
python source/basegnn.py --dataset NCI1 --gnn_type sage --runs 2
python source/basegnn.py --dataset NCI1 --gnn_type sage --runs 3
python source/basegnn.py --dataset Graph-SST2 --gnn_type gcn --runs 1
python source/basegnn.py --dataset Graph-SST2 --gnn_type gcn --runs 2
python source/basegnn.py --dataset Graph-SST2 --gnn_type gcn --runs 3
python source/basegnn.py --dataset Graph-SST2 --gnn_type gat --runs 1
python source/basegnn.py --dataset Graph-SST2 --gnn_type gat --runs 2
python source/basegnn.py --dataset Graph-SST2 --gnn_type gat --runs 3
python source/basegnn.py --dataset Graph-SST2 --gnn_type gin --runs 1
python source/basegnn.py --dataset Graph-SST2 --gnn_type gin --runs 2
python source/basegnn.py --dataset Graph-SST2 --gnn_type gin --runs 3
python source/basegnn.py --dataset Graph-SST2 --gnn_type sage --runs 1
python source/basegnn.py --dataset Graph-SST2 --gnn_type sage --runs 2
python source/basegnn.py --dataset Graph-SST2 --gnn_type sage --runs 3
python source/basegnn.py --dataset ogbg_molhiv --gnn_type gcn --runs 1
python source/basegnn.py --dataset ogbg_molhiv --gnn_type gcn --runs 2
python source/basegnn.py --dataset ogbg_molhiv --gnn_type gcn --runs 3
python source/basegnn.py --dataset ogbg_molhiv --gnn_type gat --runs 1
python source/basegnn.py --dataset ogbg_molhiv --gnn_type gat --runs 2
python source/basegnn.py --dataset ogbg_molhiv --gnn_type gat --runs 3
python source/basegnn.py --dataset ogbg_molhiv --gnn_type gin --runs 1
python source/basegnn.py --dataset ogbg_molhiv --gnn_type gin --runs 2
python source/basegnn.py --dataset ogbg_molhiv --gnn_type gin --runs 3
python source/basegnn.py --dataset ogbg_molhiv --gnn_type sage --runs 1
python source/basegnn.py --dataset ogbg_molhiv --gnn_type sage --runs 2
python source/basegnn.py --dataset ogbg_molhiv --gnn_type sage --runs 3